### PR TITLE
Provide the ability to display information of the projects installed via 'cgr'

### PR DESCRIPTION
**Pull request by uberhacker**

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
This fails on projects that have been removed via `cgr remove org/proj`. In this case, Composer leaves behind a composer.json with an empty `require` section.

**Comment by uberhacker** [comment]
What is your suggested fix?

**Comment by greg-1-anderson** [comment]
Thinking about it. Perhaps cgr could be more destructive during a remove; however, I think it would be good to detect and skip empty projects.

**Comment by greg-1-anderson** [comment]
It would probably be sufficient to just let `composer` error out on removed projects as it currently does, as long as `cgr info` kept going after one failure. With the current implementation, you don't see the rest of your installed projects once you hit one that has been removed.

**Comment by greg-1-anderson** [comment]
screen shot 2016-12-27 at 11 32 17 am

Example of acceptable output -- last installed project is removed. Removing the first project causes problems, though.

**Comment by greg-1-anderson** [comment]
Thanks for this. Making `info` not fail fast would be a worthwhile follow-on exercise if you feel like it. Or wait for something like https://github.com/composer/composer/pull/6001

**Pull request merged**
